#!/usr/bin/env bash
# =============================================================================
# cleanup_memory_bank.sh
# Detects and removes nested/duplicate memory-bank and implementation-plans
# folders, deletes redundant files, and normalises the directory structure.
# Safe to run locally or from GitHub Actions.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || pwd)"
LOG_FILE="${REPO_ROOT}/.github/cleanup-log.txt"
DRY_RUN="${DRY_RUN:-false}"
CHANGED=0

log()  { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*" | tee -a "$LOG_FILE"; }
die()  { log "ERROR: $*"; exit 1; }

safe_remove() {
  local target="$1"
    if [[ "$DRY_RUN" == "true" ]]; then
        log "DRY-RUN would remove: $target"
          else
              rm -rf "$target"
                  log "REMOVED $target"
                      CHANGED=1
                        fi
                        }

                        safe_remove_file() {
                          local target="$1"
                            if [[ "$DRY_RUN" == "true" ]]; then
                                log "DRY-RUN would remove file: $target"
                                  else
                                      rm -f "$target"
                                          log "REMOVED $target"
                                              CHANGED=1
                                                fi
                                                }

                                                remove_nested_memory_bank() {
                                                  log "=== Checking for nested memory-bank folders ==="
                                                    mapfile -t all_mb > >(find "$REPO_ROOT" -type d -name "memory-bank" | sort -r)
                                                      for dir in "${all_mb[@]}"; do
                                                          rel="${dir#"$REPO_ROOT/"}"
                                                              parent_check="${dir%/memory-bank}"
                                                                  if [[ "$parent_check" == *"/memory-bank/"* ]] || \
                                                                         [[ "$parent_check" == *"/memory-bank" && "$parent_check" != "$REPO_ROOT" ]]; then
                                                                               log "NESTED $rel (inside another memory-bank)"
                                                                                     safe_remove "$dir"
                                                                                         fi
                                                                                           done
                                                                                           }

                                                                                           remove_nested_implementation_plans() {
                                                                                             log "=== Checking for nested implementation-plans folders ==="
                                                                                               mapfile -t all_ip > >(find "$REPO_ROOT" -type d -name "implementation-plans" | sort -r)
                                                                                                 for dir in "${all_ip[@]}"; do
                                                                                                     rel="${dir#"$REPO_ROOT/"}"
                                                                                                         parent_check="${dir%/implementation-plans}"
                                                                                                             if [[ "$parent_check" == *"/implementation-plans/"* ]] || \
                                                                                                                    [[ "$parent_check" == *"/implementation-plans" && "$parent_check" != "$REPO_ROOT" ]]; then
                                                                                                                          log "NESTED $rel (inside another implementation-plans)"
                                                                                                                                safe_remove "$dir"
                                                                                                                                    fi
                                                                                                                                      done
                                                                                                                                      }
                                                                                                                                      
                                                                                                                                      remove_duplicate_directories() {
                                                                                                                                        local dirname="$1"
                                                                                                                                          log "=== Checking for duplicate '$dirname' folders ==="
                                                                                                                                            declare -A seen_parents
                                                                                                                                              mapfile -t dirs > >(find "$REPO_ROOT" -type d -name "$dirname" | sort)
                                                                                                                                                for dir in "${dirs[@]}"; do
                                                                                                                                                    parent="$(dirname "$dir")"
                                                                                                                                                        rel="${dir#"$REPO_ROOT/"}"
                                                                                                                                                            if [[ -v "seen_parents[$parent]" ]]; then
                                                                                                                                                                  log "DUPLICATE $rel (parent already has a '$dirname')"
                                                                                                                                                                        safe_remove "$dir"
                                                                                                                                                                            else
                                                                                                                                                                                  seen_parents["$parent"]="$dir"
                                                                                                                                                                                        log "KEEP $rel"
                                                                                                                                                                                            fi
                                                                                                                                                                                              done
                                                                                                                                                                                              }
                                                                                                                                                                                              
                                                                                                                                                                                              remove_redundant_files() {
                                                                                                                                                                                                log "=== Removing redundant files ==="
                                                                                                                                                                                                  local -a junk_patterns=("*.orig" "*.bak" "*.tmp" ".DS_Store" "Thumbs.db" "desktop.ini" "*.pyc" "__pycache__")
                                                                                                                                                                                                    for pattern in "${junk_patterns[@]}"; do
                                                                                                                                                                                                        while IFS= read -r -d '' f; do
                                                                                                                                                                                                              rel="${f#"$REPO_ROOT/"}"
                                                                                                                                                                                                                    if [[ -d "$f" ]]; then
                                                                                                                                                                                                                            safe_remove "$f"
                                                                                                                                                                                                                                  else
                                                                                                                                                                                                                                          safe_remove_file "$f"
                                                                                                                                                                                                                                                fi
                                                                                                                                                                                                                                                    done > >(find "$REPO_ROOT" -name "$pattern" -not -path "*/.git/*" -print0 2>/dev/null)
                                                                                                                                                                                                                                                      done
                                                                                                                                                                                                                                                        while IFS= read -r -d '' d; do
                                                                                                                                                                                                                                                            [[ "$(basename "$d")" == "memory-bank" ]] && continue
                                                                                                                                                                                                                                                                [[ "$(basename "$d")" == "implementation-plans" ]] && continue
                                                                                                                                                                                                                                                                    safe_remove "$d"
                                                                                                                                                                                                                                                                      done > >(find "$REPO_ROOT/memory-bank" "$REPO_ROOT/implementation-plans" \
                                                                                                                                                                                                                                                                                      -mindepth 1 -type d -empty -print0 2>/dev/null)
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      ensure_canonical_structure() {
                                                                                                                                                                                                                                                                                        log "=== Ensuring canonical directory structure ==="
                                                                                                                                                                                                                                                                                          for canon in "memory-bank" "implementation-plans"; do
                                                                                                                                                                                                                                                                                              target="$REPO_ROOT/$canon"
                                                                                                                                                                                                                                                                                                  if [[ ! -d "$target" ]]; then
                                                                                                                                                                                                                                                                                                        mkdir -p "$target"
                                                                                                                                                                                                                                                                                                              touch "$target/.gitkeep"
                                                                                                                                                                                                                                                                                                                    log "CREATED $canon/"
                                                                                                                                                                                                                                                                                                                          CHANGED=1
                                                                                                                                                                                                                                                                                                                              else
                                                                                                                                                                                                                                                                                                                                    log "EXISTS $canon/"
                                                                                                                                                                                                                                                                                                                                        fi
                                                                                                                                                                                                                                                                                                                                          done
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                          write_recursion_guard() {
                                                                                                                                                                                                                                                                                                                                            log "=== Writing recursion-guard files ==="
                                                                                                                                                                                                                                                                                                                                              for canon in "memory-bank" "implementation-plans"; do
                                                                                                                                                                                                                                                                                                                                                  target="$REPO_ROOT/$canon/.cleanup-guard"
                                                                                                                                                                                                                                                                                                                                                      if [[ "$DRY_RUN" == "true" ]]; then
                                                                                                                                                                                                                                                                                                                                                            log "DRY-RUN would write guard: $canon/.cleanup-guard"
                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                      printf '# RECURSION GUARD\n# Managed by cleanup_memory_bank.sh\n# Do NOT nest memory-bank or implementation-plans folders here.\nCANONICAL=true\n' > "$target"
                                                                                                                                                                                                                                                                                                                                                                            log "GUARD $canon/.cleanup-guard written"
                                                                                                                                                                                                                                                                                                                                                                                  CHANGED=1
                                                                                                                                                                                                                                                                                                                                                                                      fi
                                                                                                                                                                                                                                                                                                                                                                                        done
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                        main() {
                                                                                                                                                                                                                                                                                                                                                                                          mkdir -p "$(dirname "$LOG_FILE")"
                                                                                                                                                                                                                                                                                                                                                                                            log "======================================================="
                                                                                                                                                                                                                                                                                                                                                                                              log "  memory-bank cleanup  DRY_RUN=$DRY_RUN"
                                                                                                                                                                                                                                                                                                                                                                                                log "  REPO_ROOT: $REPO_ROOT"
                                                                                                                                                                                                                                                                                                                                                                                                  log "======================================================="
                                                                                                                                                                                                                                                                                                                                                                                                    remove_nested_memory_bank
                                                                                                                                                                                                                                                                                                                                                                                                      remove_nested_implementation_plans
                                                                                                                                                                                                                                                                                                                                                                                                        remove_duplicate_directories "memory-bank"
                                                                                                                                                                                                                                                                                                                                                                                                          remove_duplicate_directories "implementation-plans"
                                                                                                                                                                                                                                                                                                                                                                                                            remove_redundant_files
                                                                                                                                                                                                                                                                                                                                                                                                              ensure_canonical_structure
                                                                                                                                                                                                                                                                                                                                                                                                                write_recursion_guard
                                                                                                                                                                                                                                                                                                                                                                                                                  log "  Cleanup complete. CHANGED=$CHANGED"
                                                                                                                                                                                                                                                                                                                                                                                                                    [[ "$CHANGED" == "1" ]] && exit 2 || exit 0
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                    main "$@"
